feat: add support for additional pod annotations/labels
cert-manager/trust-manager pull request #116
Opened 2023-02-20 16:43 UTC by jaygridley

2023-04-28 07:49 UTC, jaygridley commented
/assign @joshvanl

2023-08-16 09:41 UTC, jaygridley commented
/ok-to-test

2023-08-16 09:42 UTC, jaygridley commented
Hello @JoshVanL, could you have a look at this one, please?

2023-08-16 12:24 UTC, JoshVanL commented
Thanks @jaygridley!
/lgtm
/approve 
/ok-to-test

2023-08-16 13:55 UTC, JoshVanL commented
CI broken?
/retest

2023-08-18 20:14 UTC, jaygridley commented
Hi @JoshVanL, I did that, but the tests still seem to struggle to run.

2023-09-17 09:19 UTC, erikgb commented
/retest

2023-10-26 09:20 UTC, jaygridley commented
/retest-required

2023-10-26 09:53 UTC, jaygridley commented
@JoshVanL I think this is ready to go

2023-10-27 23:12 UTC, erikgb requested changes
Thanks! A couple of minor nits, but that might be because the project has been renamed since the PR was created. Sorry for the delay.

2023-10-27 23:12 UTC, erikgb commented on deploy/charts/trust-manager/values.yaml
> +  # -- Pod labels to add to trust pods.
```suggestion
  # -- Pod labels to add to trust-manager pods.
```

2023-10-27 23:12 UTC, erikgb commented on deploy/charts/trust-manager/values.yaml
> +  # -- Pod annotations to add to trust pods.
```suggestion
  # -- Pod annotations to add to trust-manager pods.
```

2023-10-30 09:17 UTC, erikgb commented
@jaygridley Maybe you should rebase/squash all commits into a single one? And regen the Helm docs.

2023-10-30 19:04 UTC, JoshVanL commented
Cheers! 
/lgtm

2023-10-30 19:05 UTC, merged