Allow enabling hostNetwork mode in Helm chart
cert-manager/trust-manager pull request #156
Opened 2023-08-03 10:10 UTC by cablespaghetti

Taking inspiration from the cert-manager helm chart, this fixes the prematurely closed #62 by making it possible to start the trust manager pods in hostNetwork mode. I've tested this on my cluster and it fixes issues with EKS running with a non-standard CNI.

2023-08-17 12:29 UTC, ChevronTango commented
I just raised https://github.com/cert-manager/trust-manager/issues/159 as we've been encountering this issue. Glad to see that there's already a fix in the works. It's a simple enough change but we'd be very ken to see this merged and released ASAP.

2023-09-04 14:47 UTC, J1235 commented
We're using the fairly standard Calico CNI with EKS and this PR would solve the problems we see when doing updates, as confirmed by a patch we've had to do after deployment.

2023-09-04 15:33 UTC, erikgb requested changes
/ok-to-test

2023-09-04 15:35 UTC, erikgb commented
/retest

2023-09-04 15:44 UTC, erikgb commented
@cablespaghetti Thanks for this. "Please run 'make -s update-helm-docs" to fix the build.

2023-09-17 08:56 UTC, cablespaghetti commented
Sorry for the delay. I've sorted this now.

2023-09-17 09:03 UTC, erikgb commented
@cablespaghetti It seems like the docs marker for the new Helm value is not properly formatted. Could you fix this and regenerate the docs - to ensure the new value is documented in the Helm README?

2023-09-17 14:03 UTC, erikgb commented
/retest

2023-09-17 14:11 UTC, erikgb approved these changes
/lgtm

2023-09-22 09:58 UTC, J1235 commented
Nearly there?

2023-09-29 10:36 UTC, inteon commented on deploy/charts/trust-manager/README.md
> +| app.hostNetwork | bool | `false` | Specifies if the app should be started in hostNetwork mode. Required for use in some managed kubernetes clusters (such as AWS EKS) with custom CNI. |
I think this should be a webhook option (so `app.webhook.hostNetwork`)

2023-09-29 10:38 UTC, inteon commented on deploy/charts/trust-manager/README.md
> +| app.hostNetwork | bool | `false` | Specifies if the app should be started in hostNetwork mode. Required for use in some managed kubernetes clusters (such as AWS EKS) with custom CNI. |
Also, I think we want to set `dnsPolicy: ClusterFirstWithHostNet` when hostNetwork is enabled (based on what we have in cert-manager): https://github.com/cert-manager/cert-manager/blob/ef3b66aebafa8467ecceb2e8567b4d62b400b2bb/deploy/charts/cert-manager/templates/webhook-deployment.yaml#L58-L60.

2023-10-11 11:28 UTC, cablespaghetti commented
I think this is good to go now.

2023-10-11 11:45 UTC, inteon commented
/retest

2023-10-11 11:46 UTC, inteon commented
/lgtm
/approve

2023-10-11 11:46 UTC, inteon commented
Thanks a lot for this contribution!

2023-10-11 11:55 UTC, inteon commented
/retest

2023-10-11 12:00 UTC, inteon commented
/retest

2023-10-11 12:05 UTC, merged