Eliminate dedicated ConfigMap target cache
cert-manager/trust-manager pull request #187
Opened 2023-09-26 21:51 UTC by erikgb

This PR eliminates the dedicated target cache and fixes the TODO related to source/target ConfigMap caches. Now the cache should only cache full configmaps in source namespace and cache configmap metadata cluster-wide.

I wished to simplify this a bit before anyone tries to add secrets as targets.

I am pretty sure that ConfigMap and PartialMetadata (for configmaps) should be treated independently in caches now. But feel free to check this @inteon - if you think the tests are not covering this area well enough. I asked about this in controller-runtime channel on Slack: https://kubernetes.slack.com/archives/C02MRBMN00Z/p1695564370173869. And also had a look at https://github.com/kubernetes-sigs/controller-runtime/pull/1174. So if this isn't working as expected, I think we should create an issue in controller-runtime.

/cc @inteon

2023-09-26 22:15 UTC, erikgb commented
/retest

2023-09-26 22:38 UTC, erikgb commented
/retest

2023-09-27 05:11 UTC, inteon commented on cmd/trust-manager/app/app.go
> -							// TODO: create a seperate cache for targets and sources and only
I'm surprised that this comment is still present in the codebase. Since it has been fixed &a separate cache was added.

2023-09-27 05:11 UTC, inteon commented on cmd/trust-manager/app/app.go
> +							TypeMeta: metav1.TypeMeta{
I fear that controller runtime does not differentiate between the partial metadata object and the typed object. There will be a config collision.

2023-09-27 05:12 UTC, inteon commented on cmd/trust-manager/app/app.go
> +							TypeMeta: metav1.TypeMeta{
See #172

2023-09-27 05:17 UTC, inteon commented on cmd/trust-manager/app/app.go
> +							TypeMeta: metav1.TypeMeta{
This is the c/r code: https://github.com/kubernetes-sigs/controller-runtime/blob/v0.16.2/pkg/cache/cache.go#L304-L316

2023-09-27 07:52 UTC, inteon requested changes
I propose we keep the dedicated cache until c/r supports differentiating between partial metadata objects and full objects (see https://github.com/cert-manager/trust-manager/pull/187#discussion_r1338054159).

However, I would like to remove the `// TODO:` comment already, I think this is something that we missed in https://github.com/cert-manager/trust-manager/pull/89 (I feel like it might have been lost while rebasing).

2023-09-27 08:20 UTC, erikgb commented
> I propose we keep the dedicated cache until c/r supports differentiating between partial metadata objects and full objects

@inteon agreed! Sorry for not testing this better. It got late yesterday. 😉 I'll update the PR.

2023-09-27 17:22 UTC, erikgb commented
Replaced by https://github.com/cert-manager/trust-manager/pull/188 - ref. comment above.

2023-09-27 17:22 UTC, closed without merging