Allow permissions to put the leases in the trust-manager namespace, not the trust namespace
cert-manager/trust-manager pull request #225
Opened 2023-11-07 20:44 UTC by tspearconquest

This pull request separates the lease permissions to their own role and role binding in the namespace where trust-manager will be installed.

2023-11-07 22:36 UTC, erikgb commented
/ok-to-test

2023-11-07 22:42 UTC, erikgb commented on deploy/charts/trust-manager/templates/role.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
```suggestion
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
```

2023-11-07 22:53 UTC, erikgb requested changes
Thanks @tspearconquest. I think we should do this, but it probably deserves special attention in the release notes for our next release. As we change namespace of the leader election lease for some users, that might allow multiple trust-manager controllers to run for a short while.

2023-11-07 23:55 UTC, tspearconquest commented
Sounds good. Is there anything I need to do in order to mention this in the release notes, or will it be taken care of in the release?

2023-11-08 00:03 UTC, erikgb commented
/lgtm

2023-11-08 00:05 UTC, erikgb commented
/cc @wallrj @SgtCoDFish @inteon 

I am tempted to approve this as well, but since my approver status is very fresh, I don't want to do anything wrong. 👼

2023-11-08 04:11 UTC, SgtCoDFish approved these changes
/lgtm
/approve

Thanks for this - it makes sense to me. Really appreciate your involvement 😁

2023-11-08 04:12 UTC, merged

2024-01-02 09:22 UTC, erikgb commented
/cherrypick release-0.7